#! /bin/bash

####################################################################################################
#
# Copyright 2017 Nathanael Hübbe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
####################################################################################################

# Does not reconfigure if a config.result file is present and contains a zero,
# so you can force reconfiguration by a simple `rm config.result`.

echo "Checkpoint, \$(pwd) = '$(pwd)'"
cd /repositories/slurm

configStatus=bad
if test -e config.result && ((!$(< config.result))) ; then
	configStatus=good
fi

if test $configStatus != good ; then
	./configure --enable-debug --prefix=/usr --sysconfdir=/etc DEFAULT_SLURM_CONF=/etc/slurm.conf
	result=$?
	echo $result > config.result
	if ((result)) ; then
		exit $result
	fi
fi

make -j8 all &&
make contrib &&
make install install-data &&
make install-contrib &&
/sbin/ldconfig -n /usr/lib/slurm
